"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import ContentCard from "@/components/ContentCard";
import PageContainer from "@/components/PageContainer";

type Row = Record<string, unknown>;
type ApiResult = { ok?: boolean; message?: string; rentalPilots?: Row[]; users?: Row[]; aircraft?: Row[] };
type PilotForm = { pilotId: string; userId: string; name: string; phone: string; email: string; licenseNo: string; status: string; assignedAircraftIds: string; memo: string };
const emptyForm: PilotForm = { pilotId: "", userId: "", name: "", phone: "", email: "", licenseNo: "", status: "활성", assignedAircraftIds: "", memo: "" };
function text(value: unknown, fallback = "") { const raw = String(value ?? "").trim(); return raw || fallback; }
function splitIds(value: unknown) { return text(value).split(",").map((item) => item.trim()).filter(Boolean); }
function aircraftLabel(row: Row) { return text(row.aircraftName || row.registrationNo || row.aircraftId, "-"); }
function badgeClass(status: unknown) { const s = text(status).replace(/\s/g, ""); if (["활성", "가능", "사용"].includes(s)) return "bg-emerald-50 text-emerald-700 border-emerald-200"; if (["대기", "휴무"].includes(s)) return "bg-amber-50 text-amber-700 border-amber-200"; if (["비활성", "정지"].includes(s)) return "bg-rose-50 text-rose-700 border-rose-200"; return "bg-blue-50 text-blue-700 border-blue-200"; }
function toForm(row: Row): PilotForm { return { pilotId: text(row.pilotId), userId: text(row.userId), name: text(row.name), phone: text(row.phone), email: text(row.email), licenseNo: text(row.licenseNo || row.licenseNumber), status: text(row.status || "활성"), assignedAircraftIds: text(row.assignedAircraftIds || row.aircraftIds), memo: text(row.memo) }; }
function SummaryCard({ title, value, tone }: { title: string; value: string | number; tone: string }) { return <ContentCard className="p-5"><div className="flex items-center gap-4"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${tone}`}><svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 21a8 8 0 0 0-16 0"/><circle cx="12" cy="7" r="4"/></svg></div><div><div className="text-sm font-black text-[#36506d]">{title}</div><div className="mt-1 text-[28px] font-black leading-none text-[#10213f]">{value}</div></div></div></ContentCard>; }

export default function RentalPilotsPage() {
  const [pilots, setPilots] = useState<Row[]>([]);
  const [users, setUsers] = useState<Row[]>([]);
  const [aircraft, setAircraft] = useState<Row[]>([]);
  const [form, setForm] = useState<PilotForm>(emptyForm);
  const [editing, setEditing] = useState(false);
  const [keyword, setKeyword] = useState("");
  const [statusFilter, setStatusFilter] = useState("전체");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/rental-pilots", { cache: "no-store" }); const data = (await response.json()) as ApiResult; if (!response.ok || data.ok === false) throw new Error(data.message || "렌탈 기장 데이터를 불러오지 못했습니다."); setPilots(Array.isArray(data.rentalPilots) ? data.rentalPilots : []); setUsers(Array.isArray(data.users) ? data.users : []); setAircraft(Array.isArray(data.aircraft) ? data.aircraft : []); } catch(e) { setError(e instanceof Error ? e.message : "렌탈 기장 데이터를 불러오지 못했습니다."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const statusOptions = useMemo(() => ["전체", ...Array.from(new Set(["활성", "대기", "휴무", "비활성", ...pilots.map((p) => text(p.status)).filter(Boolean)]))], [pilots]);
  const filtered = useMemo(() => { const q = keyword.trim().toLowerCase(); return pilots.filter((p) => { if (statusFilter !== "전체" && text(p.status) !== statusFilter) return false; if (!q) return true; return [p.pilotId, p.name, p.phone, p.email, p.licenseNo, p.assignedAircraftIds, p.memo].map((v) => text(v).toLowerCase()).join(" ").includes(q); }); }, [pilots, keyword, statusFilter]);
  const active = pilots.filter((p) => text(p.status) === "활성").length;
  const inactive = pilots.filter((p) => ["비활성", "정지"].includes(text(p.status))).length;
  function update(key: keyof PilotForm, value: string) { setForm((prev) => ({ ...prev, [key]: value })); }
  function reset() { setForm(emptyForm); setEditing(false); }
  function selectUser(userId: string) { const user = users.find((u) => text(u.userId) === userId); setForm((p) => ({ ...p, userId, name: user ? text(user.name) : p.name, phone: user ? text(user.phone) : p.phone, email: user ? text(user.email) : p.email })); }
  function toggleAircraft(id: string) { const current = splitIds(form.assignedAircraftIds); const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; update("assignedAircraftIds", next.join(", ")); }
  function startEdit(row: Row) { setForm(toForm(row)); setEditing(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function assignedAircraftText(value: unknown) { const ids = splitIds(value); if (!ids.length) return "미배정"; return ids.map((id) => { const row = aircraft.find((a) => [text(a.aircraftId), text(a.aircraftName), text(a.registrationNo)].includes(id)); return row ? aircraftLabel(row) : id; }).join(", "); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { if (!form.name.trim()) throw new Error("기장명을 입력하세요."); if (!form.assignedAircraftIds.trim()) throw new Error("배정 가능한 항공기를 1대 이상 선택하세요."); const response = await fetch("/api/rental-pilots", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: editing ? "update" : "add", data: { ...form, licenseType: "" } }) }); const data = (await response.json()) as ApiResult; if (!response.ok || data.ok === false) throw new Error(data.message || "렌탈 기장을 저장하지 못했습니다."); reset(); await load(); } catch(e) { setError(e instanceof Error ? e.message : "렌탈 기장을 저장하지 못했습니다."); } finally { setSaving(false); } }

  return <PageContainer title="렌탈기장관리" description="렌탈 예약 시 기장별 배정 가능한 항공기를 제한합니다.">
    <div className="grid gap-4 xl:grid-cols-4 md:grid-cols-2"><SummaryCard title="전체 기장" value={pilots.length} tone="bg-blue-50 text-blue-600"/><SummaryCard title="활성" value={active} tone="bg-emerald-50 text-emerald-600"/><SummaryCard title="비활성" value={inactive} tone="bg-rose-50 text-rose-600"/><SummaryCard title="관리 항공기" value={aircraft.length} tone="bg-violet-50 text-violet-600"/></div>
    <ContentCard className="p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-[20px] font-black text-[#10213f]">{editing ? "렌탈 기장 수정" : "렌탈 기장 등록"}</h2><p className="mt-1 text-sm font-bold text-[#6f8199]">자격 종류는 제외하고, 배정 가능한 항공기만 관리합니다.</p></div><button type="button" onClick={reset} className="ui-btn ui-btn-outline">신규 입력</button></div>{error ? <div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-black text-rose-700">{error}</div> : null}<form onSubmit={save} className="grid gap-4 xl:grid-cols-4 md:grid-cols-2"><label className="ui-label"><span>기존 회원 연결</span><select className="ui-input" value={form.userId} onChange={(e) => selectUser(e.target.value)}><option value="">선택 안 함</option>{users.map((u, i) => <option key={`${text(u.userId)}-${i}`} value={text(u.userId)}>{text(u.name)} / {text(u.userId)}</option>)}</select></label><label className="ui-label"><span>기장명</span><input className="ui-input" value={form.name} onChange={(e) => update("name", e.target.value)} /></label><label className="ui-label"><span>연락처</span><input className="ui-input" value={form.phone} onChange={(e) => update("phone", e.target.value)} /></label><label className="ui-label"><span>상태</span><select className="ui-input" value={form.status} onChange={(e) => update("status", e.target.value)}><option>활성</option><option>대기</option><option>휴무</option><option>비활성</option></select></label><label className="ui-label"><span>이메일</span><input className="ui-input" value={form.email} onChange={(e) => update("email", e.target.value)} /></label><label className="ui-label"><span>면장번호</span><input className="ui-input" value={form.licenseNo} onChange={(e) => update("licenseNo", e.target.value)} /></label><label className="ui-label xl:col-span-2"><span>메모</span><input className="ui-input" value={form.memo} onChange={(e) => update("memo", e.target.value)} /></label><div className="xl:col-span-4"><div className="mb-2 text-sm font-black text-[#395270]">배정 가능한 항공기</div><div className="rounded-2xl border border-[#dbe5f1] bg-white p-3"><div className="flex flex-wrap gap-2">{aircraft.map((a, i) => { const id = text(a.aircraftId); const selected = splitIds(form.assignedAircraftIds).includes(id); return <button type="button" key={`${id}-${i}`} onClick={() => toggleAircraft(id)} className={`rounded-xl border px-3 py-2 text-xs font-black ${selected ? "border-[#1264f4] bg-[#edf4ff] text-[#1264f4]" : "border-[#dbe5f1] bg-[#f8fbff] text-[#536985]"}`}>{aircraftLabel(a)}</button>; })}</div></div></div><div className="flex gap-2 xl:col-span-4"><button disabled={saving} className="ui-btn ui-btn-primary">{saving ? "저장 중" : editing ? "수정 저장" : "등록"}</button><button type="button" onClick={reset} className="ui-btn ui-btn-outline">초기화</button></div></form></ContentCard>
    <ContentCard className="p-5"><div className="grid gap-3 xl:grid-cols-[220px_minmax(320px,1fr)] md:grid-cols-2"><select className="ui-input" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}>{statusOptions.map((s) => <option key={s}>{s === "전체" ? "상태 전체" : s}</option>)}</select><input className="ui-input" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="기장명, 연락처, 이메일, 항공기 검색" /></div></ContentCard>
    <ContentCard className="overflow-hidden p-0"><div className="flex items-center justify-between px-6 py-5"><h2 className="text-[18px] font-black text-[#10213f]">렌탈 기장 목록</h2><span className="ui-badge bg-[#f4f8fd] text-[#526a89] border-[#dbe5f1]">표시 {filtered.length}건</span></div><div className="overflow-x-auto px-6 pb-6"><table className="ui-table min-w-[1040px] overflow-hidden rounded-2xl border border-[#dbe5f1]"><thead><tr><th>기장ID</th><th>기장명</th><th>연락처</th><th>이메일</th><th>면장번호</th><th>상태</th><th>배정 항공기</th><th className="text-right">관리</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="text-center text-[#6f8199]">불러오는 중입니다.</td></tr> : null}{!loading && filtered.length === 0 ? <tr><td colSpan={8} className="text-center text-[#6f8199]">표시할 기장이 없습니다.</td></tr> : null}{!loading && filtered.map((r, i) => <tr key={`${text(r.pilotId)}-${i}`}><td className="font-black text-[#10213f]">{text(r.pilotId, "-")}</td><td>{text(r.name, "-")}</td><td>{text(r.phone, "-")}</td><td>{text(r.email, "-")}</td><td>{text(r.licenseNo || r.licenseNumber, "-")}</td><td><span className={`ui-badge ${badgeClass(r.status)}`}>{text(r.status, "-")}</span></td><td>{assignedAircraftText(r.assignedAircraftIds || r.aircraftIds)}</td><td className="text-right"><button className="ui-btn ui-btn-outline" onClick={() => startEdit(r)}>수정</button></td></tr>)}</tbody></table></div></ContentCard>
  </PageContainer>;
}
