"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import ContentCard from "@/components/ContentCard";
import PageContainer from "@/components/PageContainer";

type CourseRow = { courseId?: string; courseType?: string; courseName?: string; durationMinutes?: string | number; defaultMinutes?: string | number; price?: string | number; defaultAmount?: string | number; active?: string; memo?: string; createdAt?: string; updatedAt?: string; sortOrder?: string | number };
type SettingRow = { key?: string; value?: string; memo?: string };
type ApiResponse = { ok: boolean; message?: string; courseCatalog?: CourseRow[]; settings?: SettingRow[] };

const emptyForm: CourseRow = { courseId: "", courseType: "체험비행", courseName: "", durationMinutes: 60, price: 0, active: "Y", memo: "" };
const fallbackCourseTypes = ["체험비행", "교육비행", "렌탈비행", "자가비행", "정비", "기타"];

function valueText(value: unknown) { return String(value ?? "").trim(); }
function numberText(value: unknown) { const n = Number(valueText(value).replace(/,/g, "")); return Number.isNaN(n) ? "0" : String(n); }
function formatCurrency(value: unknown) { const n = Number(numberText(value)); return n ? `${n.toLocaleString("ko-KR")}원` : "-"; }
function formatMinutes(value: unknown) { const m = Number(numberText(value)); if (!m) return "-"; if (m % 60 === 0) return `${m / 60}시간`; if (m > 60) return `${Math.floor(m / 60)}시간 ${m % 60}분`; return `${m}분`; }
function uniqueValues(values: string[]) { return Array.from(new Set(values.map((v) => v.trim()).filter(Boolean))); }
function settingValues(settings: SettingRow[], key: string, fallback: string[]) { return uniqueValues([...settings.filter((s) => valueText(s.key) === key).map((s) => valueText(s.value)), ...fallback]); }
function normalizeCourse(row: CourseRow): CourseRow { return { ...row, courseId: valueText(row.courseId), courseType: valueText(row.courseType), courseName: valueText(row.courseName), durationMinutes: numberText(row.durationMinutes || row.defaultMinutes), defaultMinutes: numberText(row.durationMinutes || row.defaultMinutes), price: numberText(row.price || row.defaultAmount), defaultAmount: numberText(row.price || row.defaultAmount), active: valueText(row.active) || "Y", memo: valueText(row.memo) }; }
function badgeClass(active: unknown) { const v = valueText(active); if (v === "N" || v === "비활성") return "bg-rose-50 text-rose-700 border-rose-200"; return "bg-emerald-50 text-emerald-700 border-emerald-200"; }
function SummaryCard({ title, value, tone }: { title: string; value: string | number; tone: string }) { return <ContentCard className="p-5"><div className="flex items-center gap-4"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${tone}`}><svg viewBox="0 0 24 24" className="h-6 w-6" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 6h16M4 12h16M4 18h10"/></svg></div><div><div className="text-sm font-black text-[#36506d]">{title}</div><div className="mt-1 text-[28px] font-black leading-none text-[#10213f]">{value}</div></div></div></ContentCard>; }

export default function CourseCatalogPage() {
  const [courses, setCourses] = useState<CourseRow[]>([]);
  const [settings, setSettings] = useState<SettingRow[]>([]);
  const [form, setForm] = useState<CourseRow>(emptyForm);
  const [selectedId, setSelectedId] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [searchText, setSearchText] = useState("");
  const [typeFilter, setTypeFilter] = useState("전체");
  const [activeFilter, setActiveFilter] = useState("전체");

  const courseTypes = useMemo(() => settingValues(settings, "bookingType", fallbackCourseTypes), [settings]);
  async function loadData() { setLoading(true); setErrorMessage(""); try { const response = await fetch("/api/course-catalog", { cache: "no-store" }); const data = (await response.json()) as ApiResponse; if (!response.ok || !data.ok) throw new Error(data.message || "코스 데이터를 불러오지 못했습니다."); setCourses((data.courseCatalog || []).map(normalizeCourse)); setSettings(data.settings || []); } catch (e) { setErrorMessage(e instanceof Error ? e.message : "코스 데이터를 불러오지 못했습니다."); } finally { setLoading(false); } }
  useEffect(() => { void loadData(); }, []);

  const filteredCourses = useMemo(() => { const q = searchText.trim().toLowerCase(); return courses.filter((item) => { if (typeFilter !== "전체" && valueText(item.courseType) !== typeFilter) return false; if (activeFilter !== "전체" && valueText(item.active) !== activeFilter) return false; if (!q) return true; return [item.courseId, item.courseType, item.courseName, item.memo].map(valueText).join(" ").toLowerCase().includes(q); }).sort((a, b) => valueText(a.courseName).localeCompare(valueText(b.courseName), "ko")); }, [courses, searchText, typeFilter, activeFilter]);
  const totalCount = courses.length;
  const activeCount = courses.filter((item) => valueText(item.active) !== "N").length;
  const experienceCount = courses.filter((item) => valueText(item.courseType) === "체험비행").length;
  const rentalCount = courses.filter((item) => valueText(item.courseType) === "렌탈비행").length;

  function updateField<K extends keyof CourseRow>(key: K, value: CourseRow[K]) { setForm((prev) => ({ ...prev, [key]: value })); }
  function resetForm() { setForm(emptyForm); setSelectedId(""); setSuccessMessage(""); setErrorMessage(""); }
  function startEdit(item: CourseRow) { const normalized = normalizeCourse(item); setSelectedId(valueText(normalized.courseId)); setForm(normalized); setSuccessMessage(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function saveCourse(event: FormEvent) { event.preventDefault(); setSaving(true); setErrorMessage(""); setSuccessMessage(""); try { if (!valueText(form.courseName)) throw new Error("코스명을 입력하세요."); const payload = normalizeCourse(form); const response = await fetch("/api/course-catalog", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: selectedId ? "update" : "add", data: payload }) }); const data = (await response.json()) as ApiResponse; if (!response.ok || !data.ok) throw new Error(data.message || "코스를 저장하지 못했습니다."); setSuccessMessage(selectedId ? "코스 정보를 수정했습니다." : "코스를 추가했습니다."); resetForm(); await loadData(); } catch (e) { setErrorMessage(e instanceof Error ? e.message : "코스를 저장하지 못했습니다."); } finally { setSaving(false); } }

  return <PageContainer title="코스관리" description="예약 유형별 코스명, 소요시간, 금액, 사용 여부를 관리합니다. 순서값은 사용하지 않습니다.">
    <div className="grid gap-4 xl:grid-cols-4 md:grid-cols-2"><SummaryCard title="전체 코스" value={totalCount} tone="bg-blue-50 text-blue-600"/><SummaryCard title="사용 코스" value={activeCount} tone="bg-emerald-50 text-emerald-600"/><SummaryCard title="체험비행" value={experienceCount} tone="bg-violet-50 text-violet-600"/><SummaryCard title="렌탈비행" value={rentalCount} tone="bg-amber-50 text-amber-600"/></div>
    <ContentCard className="p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-[20px] font-black text-[#10213f]">{selectedId ? "코스 수정" : "코스 추가"}</h2><p className="mt-1 text-sm font-bold text-[#6f8199]">코스 선택 시 종료시간 자동 계산에 사용됩니다.</p></div><button type="button" onClick={resetForm} className="ui-btn ui-btn-outline">신규 입력</button></div>{successMessage ? <div className="mb-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-black text-emerald-700">{successMessage}</div> : null}{errorMessage ? <div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-black text-rose-700">{errorMessage}</div> : null}<form onSubmit={saveCourse} className="grid gap-4 xl:grid-cols-4 md:grid-cols-2"><label className="ui-label"><span>예약 유형</span><select className="ui-input" value={valueText(form.courseType)} onChange={(e) => updateField("courseType", e.target.value)}>{courseTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><label className="ui-label xl:col-span-2"><span>코스명</span><input className="ui-input" value={valueText(form.courseName)} onChange={(e) => updateField("courseName", e.target.value)} placeholder="예: 서해안 코스" /></label><label className="ui-label"><span>사용 여부</span><select className="ui-input" value={valueText(form.active) || "Y"} onChange={(e) => updateField("active", e.target.value)}><option value="Y">사용</option><option value="N">비활성</option></select></label><label className="ui-label"><span>소요시간(분)</span><input className="ui-input" value={valueText(form.durationMinutes)} onChange={(e) => updateField("durationMinutes", e.target.value)} placeholder="60" /></label><label className="ui-label"><span>금액</span><input className="ui-input" value={valueText(form.price)} onChange={(e) => updateField("price", e.target.value)} placeholder="0" /></label><label className="ui-label xl:col-span-2"><span>메모</span><input className="ui-input" value={valueText(form.memo)} onChange={(e) => updateField("memo", e.target.value)} /></label><div className="flex gap-2 xl:col-span-4"><button disabled={saving} className="ui-btn ui-btn-primary">{saving ? "저장 중" : selectedId ? "수정 저장" : "코스 추가"}</button><button type="button" onClick={resetForm} className="ui-btn ui-btn-outline">초기화</button></div></form></ContentCard>
    <ContentCard className="p-5"><div className="grid gap-3 xl:grid-cols-[220px_180px_minmax(320px,1fr)] md:grid-cols-2"><select className="ui-input" value={typeFilter} onChange={(e) => setTypeFilter(e.target.value)}><option value="전체">유형 전체</option>{courseTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><select className="ui-input" value={activeFilter} onChange={(e) => setActiveFilter(e.target.value)}><option value="전체">사용 여부 전체</option><option value="Y">사용</option><option value="N">비활성</option></select><input className="ui-input" value={searchText} onChange={(e) => setSearchText(e.target.value)} placeholder="코스명, 유형, 메모 검색" /></div></ContentCard>
    <ContentCard className="overflow-hidden p-0"><div className="flex items-center justify-between px-6 py-5"><h2 className="text-[18px] font-black text-[#10213f]">코스 목록</h2><span className="ui-badge bg-[#f4f8fd] text-[#526a89] border-[#dbe5f1]">표시 {filteredCourses.length}건</span></div><div className="overflow-x-auto px-6 pb-6"><table className="ui-table min-w-[980px] overflow-hidden rounded-2xl border border-[#dbe5f1]"><thead><tr><th>코스ID</th><th>예약 유형</th><th>코스명</th><th>소요시간</th><th>금액</th><th>사용 여부</th><th>메모</th><th className="text-right">관리</th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="text-center text-[#6f8199]">불러오는 중입니다.</td></tr> : null}{!loading && filteredCourses.length === 0 ? <tr><td colSpan={8} className="text-center text-[#6f8199]">표시할 코스가 없습니다.</td></tr> : null}{!loading && filteredCourses.map((item) => <tr key={valueText(item.courseId) || `${valueText(item.courseType)}-${valueText(item.courseName)}`}><td className="font-black text-[#10213f]">{valueText(item.courseId) || "-"}</td><td>{valueText(item.courseType)}</td><td className="font-black text-[#10213f]">{valueText(item.courseName)}</td><td>{formatMinutes(item.durationMinutes)}</td><td>{formatCurrency(item.price)}</td><td><span className={`ui-badge ${badgeClass(item.active)}`}>{valueText(item.active) === "N" ? "비활성" : "사용"}</span></td><td className="max-w-[220px] truncate">{valueText(item.memo) || "-"}</td><td className="text-right"><button type="button" onClick={() => startEdit(item)} className="ui-btn ui-btn-outline">수정</button></td></tr>)}</tbody></table></div></ContentCard>
  </PageContainer>;
}
